name: rpm

on:
  # Let other workflows call this workflow
  workflow_call:
  # Run on pull requests too
  pull_request:
    types:
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel previous runs
  cancel-in-progress: true

jobs:
  build-job:

    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: sudo sh ./configure

    - name: Build
      run: make rpm
