name: rpm

on:
  workflow_call:
    inputs:
      upload:
        description: Whether or not to upload the finished build
        required: false
        type: boolean

jobs:
  build-job:

    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: sudo sh ./configure

    - name: Build
      run: make rpm

    - name: Upload
      if: inputs.upload
      uses: actions/upload-artifact@v3
      with:
        name: RPMS
        path: ./RPMS/
