name: Add rpms to Releases

on:
  push:
    branches:
      - master
    tags:
      - v[0-9].[0-9]+.[0-9]+-[0-9]+

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build

      - uses: actions/upload-artifact@v3
        with:
          name: RPMS
          path: ./RPMS/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    # Don't run until the build job succeeds
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: RPMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.rpm"
          generate_release_notes: true
