name: CD

on:
  # Only run CD when a new tag is created.
  push:
    tags: "v*.*.*"

jobs:

  # Re-use the build workflow to make a new build.
  build-job:
    uses: ./.github/workflows/build.yml
    with:
      # Remember to upload the built artifacts
      upload: true

  # Separate job for release!
  release-job:
    # Don't run until the build job succeeds
    needs: build-job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: RPMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.rpm"
          generate_release_notes: true
