name: CD

on:
  push:
    branches: master
    # tags: "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: RPMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.rpm"
          body: Test release please delete me
          draft: true
          name: test1