name: Add rpms to Releases

on:
  # Only run when a new tag is created.
  push:
    tags: ^(0|[1-9][0-9]*)\.[0-9]*\..*

jobs:

  # Re-use the build workflow to make a new build.
  build:
    uses: ./.github/workflows/build.yml
    with:
      # Remember to upload the built artifacts
      upload: true

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: RPMS
        path: ./RPMS/

  # Separate job for release!
  release:
    # Don't run until the build job succeeds
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: RPMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.rpm"
          generate_release_notes: true
