name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: master
    # tags: "v*.*.*"

jobs:

  build-job:
    uses: ./.github/workflows/build.yml
    with:
      upload: true

  release-job:
    needs: build-job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: RPMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.rpm"
          body: Test release please delete me
          draft: true
          name: test1