name: Add rpms to Releases

on:
  pull_request:
    types:
      - ready_for_review

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build

      - uses: actions/upload-artifact@v3
        with:
          name: RPMS
          path: ./RPMS/
